version: '3'

services:
  image-server:
    container_name: nodejs
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nodejs/uploads:/usr/src/app/uploads
    ports:
      - "3000:3000"
    command: node index.js

  proxy:
    container_name: proxy
    restart: always
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes: 
      #- /etc/letsencrypt/live/irs.ddns.net:/etc/letsencrypt/live/irs.ddns.net
      - ./proxy:/etc/letsencrypt/live/irs.ddns.net
    ports:
      - 80:80