version: '3'

services:
  image-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/usr/src/app/uploads
    container_name: image-server
    restart: unless-stopped
    ports:
      - "80:3000"
    command: node index.js